# Generated by Django 4.1 on 2023-03-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
