# Generated by Django 4.1.7 on 2023-04-06 18:49

from django.db import migrations, models
import image_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=image_api.models.S3MediaStorage(), upload_to='images/'),
        ),
    ]
