# Generated by Django 4.1 on 2023-03-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("od_data_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="od_data",
            name="xml",
            field=models.FileField(upload_to="files/"),
        ),
    ]
