# Generated by Django 4.1.7 on 2023-04-06 22:13

from django.db import migrations, models
import od_data_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('od_data_api', '0002_alter_od_data_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='od_data',
            name='label',
            field=models.FileField(storage=od_data_api.models.S3MediaStorage(), upload_to=''),
        ),
    ]
