# Generated by Django 4.1 on 2023-03-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("od_data_api", "0002_alter_od_data_xml"),
    ]

    operations = [
        migrations.AlterField(
            model_name="od_data",
            name="xml",
            field=models.FileField(upload_to="od_data/"),
        ),
    ]
