# Generated by Django 4.1.7 on 2023-07-25 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0004_remove_image_image_url'),
        ('od_data_api', '0005_alter_od_data_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='labeled_od_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_api.image')),
            ],
        ),
    ]
