# Generated by Django 4.1.7 on 2023-05-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_api', '0004_alter_report_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='is_broken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
