# Generated by Django 4.1.7 on 2023-05-11 13:32

from django.db import migrations, models
import django.db.models.deletion
import image_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image_api', '0004_remove_image_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='seg_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.FileField(storage=image_api.models.S3MediaStorage(), upload_to='seg_data/labels/')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_api.image')),
            ],
        ),
    ]
